# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180629_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='tshirt', max_length=255),
            preserve_default=False,
        ),
    ]
