# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
