# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_my_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('total_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cohort', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('order_status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
